name: boxmod-dev
dependencies:
  - python=3.8
  - ipython
  - pip
  #
  # core
  - numpy
  - scipy
  - matplotlib
  - pandas
  #
  # io
  - pyyaml
  - pip:
    - parse
  #
  # viz
  - graphviz
  - python-graphviz
